### ISSUE TITLE
Autorank v3.4 causing memory leak

### ISSUE THREAD

**Issue by SullyTheUnusual** [Staartvin/Autorank-2#154]
I run a group of seven Spigot servers with Bungeecord, and since installing version 3.4, I have had 10 out-of-memory crashes in two days.  I'm not sure if there's an info I can provide to help with this problem, since the crashes don't show anything specific to Autorank.

**Comment by Staartvin** [comment]
Hmm, could you try dev build 311. I fixed a memory leak.

**Comment by SullyTheUnusual** [comment]
Ran build #317 for 9 hours then server crashed with OutOfMemoryError:

Description: Exception in server tick loop

java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:364)
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by Nentify** [comment]
These timings show something is going on with UUID storage, not sure if it's related. Also running multiple servers with Bungee and ran /ar sync.

Timings: http://timings.aikar.co/?url=9905746

**Comment by Staartvin** [comment]
If you're using build 3.4 you should upgrade to dev build 317, as there were a few leaks fixed.

**Comment by Nentify** [comment]
Is the 317 the last working build or would it be worth just using the latest one (or non-reed one(?))?

**Comment by Staartvin** [comment]
Try 317,  the others are not stable enough

**Comment by Staartvin** [comment]
Closed due to inactivity.

**Comment by SullyTheUnusual** [comment]
Just updated my servers to Spigot 1.8.3, and the latest Autorank.  Getting the same server crash and thrown exception as before.

**Comment by jjm223** [comment]
@SullyTheUnusual Despite this ticket being a year and a half old, I'd like to ask- Do you use MySQL storage with AutoRank?

**Comment by SullyTheUnusual** [comment]
When we used AutoRank, yes.  It performed well with Spigot for MC 1.7, but we've had chronic OutOfMemory exceptions with both 1.8 and 1.9.  We now use our own custom SQL triggers and CoreProtect's session data to track time and rank.
