### ISSUE TITLE
Could not find name of account with uuid

### ISSUE THREAD

**Issue by FPSUsername** [Staartvin/Autorank-2#209]
I have issues with Autorank.

Here is the log:
[15:28:17] [Server thread/INFO]: [Autorank] Loading Autorank v3.5.1-Dev-368
[15:28:40] [Server thread/INFO]: [Autorank] Enabling Autorank v3.5.1-Dev-368
[15:28:40] [Server thread/INFO]: [Autorank] Simple config file loaded
[15:28:40] [Server thread/INFO]: [Autorank] Advanced config file loaded
[15:28:40] [Server thread/INFO]: [Autorank] Settings config file loaded
[15:28:40] [Server thread/INFO]: [Autorank] Loaded stored uuids.
[15:28:40] [Server thread/INFO]: [Autorank] Loaded playerdata.
[15:28:40] [Server thread/INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[15:28:40] [Server thread/INFO]: [Autorank] Loaded libraries and dependencies
[15:28:40] [Server thread/INFO]: [Autorank] Interval check every 5 minutes.
[15:28:40] [Server thread/INFO]: [Autorank] Data file loaded
[15:28:40] [Server thread/INFO]: [Autorank] Language file loaded (lang.yml)
[15:28:40] [Server thread/INFO]: [Autorank] Using timings of: autorank
[15:28:40] [Server thread/INFO]: [Autorank] Autorank 3.5.1-Dev-368 has been enabled!
[15:28:40] [Server thread/WARN]: [Autorank] You're running a DEV version, be sure to backup your Autorank folder!
[15:28:40] [Server thread/WARN]: [Autorank] DEV versions are not guaranteed to be stable and generally shouldn't be used on big production servers with lots of players.
[15:28:58] [Thread-33/INFO]: [Autorank] Could not find name of account with uuid: '341788e9-ab90-33fd-8565-e45a66cca763'
[15:28:58] [Thread-33/WARN]: Unexpected token END OF FILE at position 0.
[15:28:58] [Thread-33/WARN]:    at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[15:28:58] [Thread-33/WARN]:    at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[15:28:58] [Thread-33/WARN]:    at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[15:28:58] [Thread-33/WARN]:    at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
[15:28:58] [Thread-33/WARN]:    at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
[15:28:58] [Thread-33/WARN]:    at java.lang.Thread.run(Thread.java:745)

Even when I delete everything on my server with that uuid (even in some .txt and other files) I get a new uuid which autorank could not find.

**Comment by Staartvin** [comment]
Hmm. What happens when you completely remove the Autorank folder (make a backup first!)? and let Autorank create a new one?

**Comment by FPSUsername** [comment]
Sorry for no response, I'll try tomorrow morning and report.

**Comment by FPSUsername** [comment]
[23:52:57] [Server thread/INFO]: [Autorank] Loading Autorank v3.5.1-Dev-368
[23:53:17] [Server thread/INFO]: [Autorank] Enabling Autorank v3.5.1-Dev-368
[23:53:17] [Server thread/INFO]: [Autorank] New Simple config file copied from jar
[23:53:17] [Server thread/INFO]: [Autorank] New Advanced config file copied from jar
[23:53:17] [Server thread/INFO]: [Autorank] New Settings config file copied from jar
[23:53:17] [Server thread/INFO]: [Autorank] Loaded stored uuids.
[23:53:17] [Server thread/INFO]: [Autorank] Loaded playerdata.
[23:53:17] [Server thread/INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[23:53:17] [Server thread/INFO]: [Autorank] Loaded libraries and dependencies
[23:53:17] [Server thread/INFO]: [Autorank] Interval check every 5 minutes.
[23:53:17] [Server thread/INFO]: [Autorank] Language file loaded (lang.yml)
[23:53:18] [Server thread/INFO]: [Autorank] Using timings of: autorank
[23:53:18] [Server thread/INFO]: [Autorank] Autorank 3.5.1-Dev-368 has been enabled!
[23:53:18] [Server thread/WARN]: [Autorank] You're running a DEV version, be sure to backup your Autorank folder!
[23:53:18] [Server thread/WARN]: [Autorank] DEV versions are not guaranteed to be stable and generally shouldn't be used on big production servers with lots of players.
[23:53:49] [Server thread/ERROR]: [Autorank] There are invalid groups defined in the config!
[23:53:49] [Server thread/ERROR]: [Autorank] Check your config!

So this is after I removed the folder. Is there any tool to remove a player (by name or uuid) from the server? (destroy all their data). Then I could remove some old accounts.

**Comment by Staartvin** [comment]
If you have completely removed the Autorank folder, and let Autorank create a new one, you should now reconfigure the AdvancedConfig to your liking and see if the problem persists.
