### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by Posse1** [Staartvin/Autorank-2#266]
Hi, everytime i startup my server it spams a lot of lines of "Could not fetch uuid of player 'xxxx'!" and "Could not get player name of uuid 'xxxx'!" is there a way to prevent that from showing up everytime?

Example screenshot: http://puu.sh/kA5hd/c8cd10c28d.png

**Comment by Staartvin** [comment]
What version of Autorank are you using?

**Comment by Posse1** [comment]
Autorank v3.6 and spigot 1.8

**Comment by Posse1** [comment]
Hi, anything yet?

**Comment by Staartvin** [comment]
Could you upgrade to the latest dev build? (back up first)

**Comment by Posse1** [comment]
Hi I upgraded to the latest dev build #443 and still see the spam in console, but its going by a little quicker and less spam than before. I also see another error:

[23:38:07] [Thread-33/INFO]: [Autorank] Could not find name of account with uuid: 'd7f3bce8-bbaa-3233-a0c3-6fdb50f43780'
[23:38:07] [Thread-33/WARN]: Unexpected token END OF FILE at position 0.
[23:38:07] [Thread-33/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[23:38:07] [Thread-33/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[23:38:07] [Thread-33/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[23:38:07] [Thread-33/WARN]: 	at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
[23:38:07] [Thread-33/WARN]: 	at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
[23:38:07] [Thread-33/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:38:07] [Thread-34/INFO]: [Autorank] Could not find name of account with uuid: '14cde900-c3d4-33a0-85fa-98c5d57d3d47'
[23:38:08] [Thread-34/WARN]: Unexpected token END OF FILE at position 0.
[23:38:08] [Thread-34/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[23:38:08] [Thread-34/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[23:38:08] [Thread-34/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[23:38:08] [Thread-34/WARN]: 	at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
[23:38:08] [Thread-34/WARN]: 	at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
[23:38:08] [Thread-34/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:38:08] [Thread-35/INFO]: [Autorank] Could not find name of account with uuid: '81189666-1ff6-3edc-aef6-753f8d7e6e0e'
[23:38:08] [Thread-35/WARN]: Unexpected token END OF FILE at position 0.
[23:38:08] [Thread-35/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[23:38:08] [Thread-35/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[23:38:08] [Thread-35/WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[23:38:08] [Thread-35/WARN]: 	at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
[23:38:08] [Thread-35/WARN]: 	at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
[23:38:08] [Thread-35/WARN]: 	at java.lang.Thread.run(Unknown Source)


screenshot of the spam also: http://puu.sh/kHcJD/32bcc3db4e.png

**Comment by Posse1** [comment]
Hi, any update on this issue?

**Comment by Staartvin** [comment]
It might be that your uuid files are (getting) corrupted. Try to use new blank files and see if that fixes things.

**Comment by Posse1** [comment]
Do you want me to remove all the files from /Autorank/uuids/ ?

**Comment by Staartvin** [comment]
If you're able to, yes!

**Comment by SioWolf** [comment]
I had this issue as well. It means that you have UUIDs in your data.yml file that do not exist in the UUIDs folder. I fixed it by deleting those UUIDs from the data.yml file.

**Comment by Nesseley** [comment]
SioWolf? 
If you are here, is there an easy way of comparing UUIDs? (I have over 1100 users registred in data.yml.) 
Also! did your server spam users that were active and registrered in data, playerdata and uuids?

**Comment by SioWolf** [comment]
I'm hoping this gets to you, I'm replying to this as an email please let me
know!

I had MySQL set up so I was able to use that to organize my users. I
organized all the entries by date and deleted all users that had been gone
over a month.

Now, thw data in the MySQl datavase needs to be copied over to your
data.yml file. I copied the users in mysql that were left and pasted them
into Microsoft word. Once you've done that the uuifs of the players and
their times are separated by tabs. You need to change that to a semicolon
and a space. I used word's replace feature to do that.

I replaced the data.yml file with this new list and it drastically lowered
the errors. The rest I found and deleted from the lost by hand.

My console did NOT spam users that were in the UUID files AND the data.yml.

**Comment by Nesseley** [comment]
SioWolf.
I got the message! :) thank you for replying so fast!

I might try to do this, but my users that gets spammed includes me.. So I'm not sure, maybe my list of users are too long? I'l try to delete Old inactive users and people with under 1 hour ontime first.

**Comment by SioWolf** [comment]
If you do keep this in mind:

Autorank does NOT use MySQL to replace local files like most plugins. MySQL
is only used to sync the data between multiple servers if you have
bungeecord or something. It still saves the data in a local file as well as
MySQL. So you can use MySQL to organize your data, but you need to update
the local file with the same changes.I'm not sure what your spam is - can
is see a copy of some of the lines?

**Comment by Nesseley** [comment]
I dont use mysql for autorank to begin with.. :/
https://gyazo.com/ab795f01f61ae46366a9145f9318e8ef
That is my spam and starts everytime i start server, or someone uses /ar leaderboard.
My leaderboard also takes WAY too long to show up in chat (because it goes trough so many uuids?)

I also get this error when stopping my server: http://pastebin.com/bWWXKxV4 Have a post on this myself, waiting for answer form Staartwin.

My server also cant find some users if they havent loggen in since last restart, så i cant check them with /ar check player, and they wont show in leaderboard until they log in. 

I tried deleting all players that had less then 55minutes played, still need to restart to check if this helped at all. If not i will try removing old data.

**Comment by Staartvin** [comment]
If you're having trouble with the Autorank leaderboard, it is definitely caused by a huge uuid list. Autorank tries to go through all your players to check where they are ranked on the ladder. I'm actually working on something that stores the cache-leaderboard so it just caches the leaderboard every once in a while.

**Comment by Staartvin** [comment]
Could you drop a link to your data.yml? I need a data.yml to test things.

**Comment by Nesseley** [comment]
Staartvin, I posted my data.yml in my own thread :) Just had to check if this guy knew how to fix mine too :)

" I'm actually working on something that stores the cache-leaderboard so it just caches the leaderboard every once in a while."
- this shounds awesome, Can't wait for it to be implemented!
