### ISSUE TITLE
Could not pass event PlayerJoinEvent to Autorank v3.7.2

### ISSUE THREAD

**Issue by TheChampTF** [Staartvin/Autorank-2#294]
[16:40:57 ERROR]: ***\* THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event PlayerJoinEvent to Autorank v3.7.2
org.bukkit.event.EventException
    at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-bc01c3a-935349e]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: com.gmail.nossr50.api.exceptions.InvalidPlayerException: That player does not exist in the database.
    at com.gmail.nossr50.api.ExperienceAPI.getOfflineProfile(ExperienceAPI.java:1037) ~[?:?]
    at com.gmail.nossr50.api.ExperienceAPI.getLevelOffline(ExperienceAPI.java:689) ~[?:?]
    at me.armar.plugins.autorank.hooks.mcmmoapi.McMMOHandler.getSkillLevel(McMMOHandler.java:105) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.requirement.McMMOSkillLevelRequirement.meetsRequirement(McMMOSkillLevelRequirement.java:78) ~[?:?]
    at me.armar.plugins.autorank.rankbuilder.ChangeGroup.checkRequirements(ChangeGroup.java:147) ~[?:?]
    at me.armar.plugins.autorank.rankbuilder.ChangeGroup.applyChange(ChangeGroup.java:80) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:81) ~[?:?]
    at me.armar.plugins.autorank.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:53) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]

**Comment by Staartvin** [comment]
It seems that Autorank tried to call a player from McMMO that they did not store. Are you still getting this error message or is it fixed?

**Comment by TheChampTF** [comment]
Might been fixed in the latest dev from McMMO, will let you know if still a issue
