### ISSUE TITLE
NullPointerException with Stats, mobs killed, and /ar check

### ISSUE THREAD

**Issue by Allu2** [Staartvin/Autorank-2#319]
Error:

```
#!java

[22:48:45 INFO]: Allyoutoo issued server command: /ar check
[22:48:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.7.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.hooks.statsapi.StatsAPIHandler.getTotalMobsKilled(StatsAPIHandler.java:307) ~[?:?]
        at me.armar.plugins.autorank.statsmanager.handlers.StatsHandler.getNormalStat(StatsHandler.java:69) ~[?:?]
        at me.armar.plugins.autorank.playerchecker.requirement.MobKillsRequirement.meetsRequirement(MobKillsRequirement.java:73) ~[?:?]
        at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:76) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:141) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:294) ~[?:?]
        at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:159) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        ... 15 more
```

What I did:
Cleared Stats users folder, joined game, ran /ar check

What happened: 
AutoRank failed to display the requirements with Internal error occurred message.
http://puu.sh/oCJWv/e6add7f431.png

What should've happen:
AutoRank should've shown me the requirements and that I have not cleared the Mob limit.

Info:
AutoRank: v3.7.3
Stats:  v3.1.0-RC-431
Spigot: CraftBukkit version git-Spigot-5a40365-b70058a (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

AdvancedConfig.yml

`````` ranks:
    default:
        requirements:
            time:
                value: 5h
            mobs killed: 
                value: 2;pig
        results:
            rank change: default;rank1
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Soldier!'
            message: 'Congratulations, you are now a Soldier.'```
``````

**Comment by Staartvin** [comment]
Could you run this version? http://62.131.38.74:8080/job/Autorank/lastSuccessfulBuild/

**Comment by Allu2** [comment]
Looks about same result
```
[23:27:00 INFO]: Allyoutoo issued server command: /ar check
[23:27:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.7.3-Dev-515
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.hooks.statsapi.StatsAPIHandler.getTotalMobsKilled(StatsAPIHandler.java:307) ~[?:?]
        at me.armar.plugins.autorank.statsmanager.handlers.StatsHandler.getNormalStat(StatsHandler.java:69) ~[?:?]
        at me.armar.plugins.autorank.playerchecker.requirement.MobKillsRequirement.meetsRequirement(MobKillsRequirement.java:73) ~[?:?]
        at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:79) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:141) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:294) ~[?:?]
        at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:159) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        ... 15 more
>```

**Comment by Staartvin** [comment]
Can you show me your MySQL table of Stats' mobs killed?

**Comment by Allu2** [comment]
Ah, forgot to mention I am using Flatfile on Stats
I attach the file it created after I joined in.

[a743b335-75f5-46b2-99c3-9a7a2ff22a53.txt](https://github.com/Armarr/Autorank-2/files/244343/a743b335-75f5-46b2-99c3-9a7a2ff22a53.txt)
