### ISSUE TITLE
Error running view and check commands

### ISSUE THREAD

**Issue by mdunlavy** [Staartvin/Autorank-2#324]
Hey, I have no idea what is causing this issue. please help.

01:02:52] [Server thread/INFO]: mdunlavy issued server command: /ar view buckingfaller
[01:02:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.7.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-685]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-685]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-685]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-685]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-685]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
    at me.armar.plugins.autorank.playerchecker.requirement.MoneyRequirement.getDescription(MoneyRequirement.java:15) ~[?:?]
    at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.getDescription(RequirementsHolder.java:153) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.PlayerChecker.getRequirementsInStringList(PlayerChecker.java:172) ~[?:?]
    at me.armar.plugins.autorank.commands.ViewCommand.onCommand(ViewCommand.java:78) ~[?:?]
    at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:159) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-685]
    ... 15 more

**Comment by mdunlavy** [comment]
Resolved.  Had an issue with Stats and not having an eco plugin on the server. once those were installed, issues resolved.
