### ISSUE TITLE
don't know why this keeps coming back

### ISSUE THREAD

**Issue by MrKiller01** [Staartvin/Autorank-2#329]
Hi, i got this weird thing, i updated my server to the latest version, and if i check now it says that i have the latest version running, yet i started to get weird console output relating to autorank...
<<code lua>>

> version
> [09:48:04 INFO]: This server is running CraftBukkit version git-Spigot-4af49dc-23da8b0 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
> [09:48:04 INFO]: Checking version, please wait...
> [09:48:05 INFO]: You are running the latest version
> list
> [09:48:07 INFO]: CONSOLE issued server command: /list
> [09:48:07 INFO]: There are 0 out of maximum 51 players online.
> [09:50:47 INFO]: [Autorank] A new day has arrived! All daily times have been reset.
> [09:50:47 WARN]: Exception in thread "Craft Scheduler Thread - 3658"
> [09:50:47 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.3 generated an exception while executing task 70
>         at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.IllegalStateException: Asynchronous entity track!
>         at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
>         at net.minecraft.server.v1_9_R2.EntityTracker.addEntity(EntityTracker.java:104)
>         at net.minecraft.server.v1_9_R2.EntityTracker.track(EntityTracker.java:80)
>         at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:19)
>         at net.minecraft.server.v1_9_R2.World.b(World.java:1024)
>         at net.minecraft.server.v1_9_R2.WorldServer.b(WorldServer.java:1126)
>         at net.minecraft.server.v1_9_R2.WorldServer.a(WorldServer.java:1091)
>         at net.minecraft.server.v1_9_R2.Chunk.addEntities(Chunk.java:757)
>         at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
>         at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
>         at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
>         at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
>         at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
>         at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:122)
>         at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:105)
>         at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:101)
>         at net.minecraft.server.v1_9_R2.World.getChunkAt(World.java:329)
>         at net.minecraft.server.v1_9_R2.World.getChunkAtWorldCoords(World.java:325)
>         at net.minecraft.server.v1_9_R2.World.getType(World.java:749)
>         at net.minecraft.server.v1_9_R2.TileEntityCommand$1.i(TileEntityCommand.java:33)
>         at net.minecraft.server.v1_9_R2.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:271)
>         at org.bukkit.craftbukkit.v1_9_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
>         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.broadcast(CraftServer.java:1288)
>         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.broadcastMessage(CraftServer.java:452)
>         at me.armar.plugins.autorank.playtimes.Playtimes.doCalendarCheck(Playtimes.java:527)
>         at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:74)
>         at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
>         at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
>         at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>         ... 3 more

<</code>>

**Comment by Staartvin** [comment]
Hmm, that's odd. I've never seen this error before. Does this error occur frequently?

**Comment by 2fast4u2** [comment]
If it helps: 1.9.4 clients cannot connect to my 1.9.2 server.

**Comment by MrKiller01** [comment]
Ehm, i've been looking at different plugins with this weird behaviour, but i thought it would be worth mentioning. I am going to upgrade after a long weekend i am now 4 versions behind, maybe it goes away by itself, maybe not, if so, i'll let you know...

**Comment by MrKiller01** [comment]
yet after updating i get again this:
`>version
[00:09:41 INFO]: This server is running CraftBukkit version git-Spigot-4af49dc-4e19de1 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
[00:09:41 INFO]: You are running the latest version
[00:13:06 INFO]: [Autorank] A new day has arrived! All daily times have been reset.
[00:13:06 WARN]: Exception in thread "Craft Scheduler Thread - 36"
[00:13:06 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.3 generated an exception while executing task 70
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
        at net.minecraft.server.v1_9_R2.EntityTracker.addEntity(EntityTracker.java:104)
        at net.minecraft.server.v1_9_R2.EntityTracker.track(EntityTracker.java:80)
        at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:19)
        at net.minecraft.server.v1_9_R2.World.b(World.java:1024)
        at net.minecraft.server.v1_9_R2.WorldServer.b(WorldServer.java:1126)
        at net.minecraft.server.v1_9_R2.WorldServer.a(WorldServer.java:1091)
        at net.minecraft.server.v1_9_R2.Chunk.addEntities(Chunk.java:757)
        at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
        at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
        at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
        at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
        at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
        at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:122)
        at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:105)
        at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:101)
        at net.minecraft.server.v1_9_R2.World.getChunkAt(World.java:329)
        at net.minecraft.server.v1_9_R2.World.getChunkAtWorldCoords(World.java:325)
        at net.minecraft.server.v1_9_R2.World.getType(World.java:749)
        at net.minecraft.server.v1_9_R2.TileEntityCommand$1.i(TileEntityCommand.java:33)
        at net.minecraft.server.v1_9_R2.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:271)
        at org.bukkit.craftbukkit.v1_9_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27)
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.broadcast(CraftServer.java:1288)
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.broadcastMessage(CraftServer.java:452)
        at me.armar.plugins.autorank.playtimes.Playtimes.doCalendarCheck(Playtimes.java:527)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:74)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
`
