### ISSUE TITLE
Strange Error Message

### ISSUE THREAD

**Issue by volantijason** [Staartvin/Autorank-2#332]
Afternoon (at least my time it is..)

I've tried setting up this plugin using the Advanced Config and after setting it up, I'm getting error messages that aren't exactly clear to me.

[11:11:24] [Craft Scheduler Thread - 9/WARN]: Exception in thread "Craft Scheduler Thread - 9" 
[11:11:24] [Craft Scheduler Thread - 9/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.3 generated an exception while executing task 70
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:100)
    at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:91)
    at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:54)
    at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:65)
    at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:84)
    at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[11:15:25] [Server thread/INFO]: Autorank has been reloaded.
[11:15:25] [Server thread/INFO]: [Autorank] Disabling Autorank v3.7.3
[11:15:25] [Server thread/INFO]: [Autorank] Autorank 3.7.3 has been disabled!
[11:15:25] [Server thread/INFO]: [Autorank] Enabling Autorank v3.7.3
[11:15:25] [Server thread/INFO]: [Autorank] Simple config file loaded
[11:15:25] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 64, column 62:
     ... ulations, you are now a Legend.'  
                                         ^

[11:15:25] [Server thread/WARN]:    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[11:15:25] [Server thread/WARN]:    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[11:15:25] [Server thread/WARN]:    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169)
[11:15:25] [Server thread/WARN]:    at me.armar.plugins.autorank.data.SimpleYamlConfiguration.<init>(SimpleYamlConfiguration.java:64)
[11:15:25] [Server thread/WARN]:    at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:220)
[11:15:25] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[11:15:25] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[11:15:25] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:15:25] [Server thread/WARN]:    at me.armar.plugins.autorank.Autorank.reload(Autorank.java:527)
[11:15:25] [Server thread/WARN]:    at me.armar.plugins.autorank.commands.ReloadCommand.onCommand(ReloadCommand.java:36)
[11:15:25] [Server thread/WARN]:    at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:159)
[11:15:25] [Server thread/WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:15:25] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:15:25] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[11:15:25] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[11:15:25] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[11:15:25] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[11:15:25] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[11:15:25] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[11:15:25] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[11:15:25] [Server thread/WARN]: Caused by: while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 64, column 62:
     ... ulations, you are now a Legend.'  
                                         ^

[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
[11:15:25] [Server thread/WARN]:    at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
[11:15:25] [Server thread/WARN]:    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[11:15:25] [Server thread/WARN]:    ... 19 more
[11:15:25] [Server thread/INFO]: [Autorank] Settings config file loaded
[11:15:25] [Server thread/INFO]: [Autorank] Internal properties file loaded
[11:15:25] [Server thread/INFO]: [Autorank] Backup data file loaded (backup-data.yml)
[11:15:25] [Server thread/INFO]: [Autorank] Loaded stored uuids.
[11:15:25] [Server thread/INFO]: [Autorank] Loaded playerdata.
[11:15:25] [Server thread/INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[11:15:25] [Server thread/INFO]: [Autorank] Loaded libraries and dependencies
[11:15:25] [Server thread/INFO]: [Autorank] Interval check every 5 minutes.
[11:15:25] [Server thread/INFO]: [Autorank] Total data file loaded
[11:15:25] [Server thread/INFO]: [Autorank] Daily data file loaded
[11:15:25] [Server thread/INFO]: [Autorank] Weekly data file loaded
[11:15:25] [Server thread/INFO]: [Autorank] Monthly data file loaded
[11:15:25] [Server thread/INFO]: [Autorank] Language file loaded (lang.yml)
[11:15:25] [Server thread/INFO]: [Autorank] Using timings of: autorank
[11:15:25] [Server thread/INFO]: [Autorank] Autorank 3.7.3 has been enabled!
[11:15:30] [Craft Scheduler Thread - 15/WARN]: Exception in thread "Craft Scheduler Thread - 15" 
[11:15:30] [Craft Scheduler Thread - 15/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.3 generated an exception while executing task 118
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:100)
    at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initAdvancedConfig(ChangeGroupBuilder.java:153)
    at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initialiseChangeGroups(ChangeGroupBuilder.java:52)
    at me.armar.plugins.autorank.rankbuilder.ChangeGroupManager.initialiseFromConfigs(ChangeGroupManager.java:47)
    at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:352)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[11:16:20] [Server thread/INFO]: Saving is already turned on.
[11:16:20] [Server thread/INFO]: Saving...
[11:16:20] [Server thread/INFO]: Saved the world

That's one of them, the other is:

22.05 11:03:15 [Server] INFO SSBVegeta issued server command: /ar check
22.05 11:03:15 [Server] ERROR null
22.05 11:03:15 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.6
22.05 11:03:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
22.05 11:03:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
22.05 11:03:15 [Server] INFO Caused by: java.lang.NullPointerException
22.05 11:03:15 [Server] INFO at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:88) ~[?:?]
22.05 11:03:15 [Server] INFO at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:90) ~[?:?]
22.05 11:03:15 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:49) ~[?:?]
22.05 11:03:15 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:326) ~[?:?]
22.05 11:03:15 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:141) ~[?:?]
22.05 11:03:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
22.05 11:03:15 [Server] INFO ... 15 more

I'm literally so confused as to this. I've tried v3.7.3 but now running 3.7.2.

Thanks in advance!

**Comment by volantijason** [comment]
Not sure if this works but bump?

**Comment by MitesMC** [comment]
In case you haven't solved this issue, this error message tells you exactly what the problem is:

[11:15:25] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token found character '\t(TAB)' that cannot start any token. **(Do not use \t(TAB) for indentation)** in 'string', line 64, column 62:

Do not use TAB when setting up your config and settings. **Always use spaces**. This is true for most plugins so better check your spacing if it's using a TAB or actual SPACES.
