### ISSUE TITLE
Nodes must be provided

### ISSUE THREAD

**Issue by TheChampTF** [Staartvin/Autorank-2#369]
[10:49:33 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.3 generated an exception while executing task 123
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Nodes must be provided.
    at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
    at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
    at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
    at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
    at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
    at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
    at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
    at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
    at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
    at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68)
    at me.armar.plugins.autorank.data.SimpleYamlConfiguration.save(SimpleYamlConfiguration.java:97)
    at me.armar.plugins.autorank.internalproperties.InternalProperties.setCachedLeaderboard(InternalProperties.java:66)
    at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:301)
    at me.armar.plugins.autorank.playtimes.Playtimes$2.run(Playtimes.java:564)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

**Comment by recon88** [comment]
Having the same issue

**Comment by Volander** [comment]
bump

**Comment by Staartvin** [comment]
Please update to the most recent version of Autorank and see if that solves the problem.

**Comment by Gartentrulla** [comment]
I have the same Problem for spigot 1.13.2. Can you fix this please?

[03:03:58] [Craft Scheduler Thread - 7/WARN]: [Autorank] Plugin Autorank v4.2.6 generated an exception while executing task 67
java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at me.armar.plugins.autorank.config.SimpleYamlConfiguration.saveFile(SimpleYamlConfiguration.java:94) ~[?:?]
	at me.armar.plugins.autorank.config.AbstractConfig.saveConfig(AbstractConfig.java:55) ~[?:?]
	at me.armar.plugins.autorank.config.InternalPropertiesConfig.setLeaderboardLastUpdateTime(InternalPropertiesConfig.java:161) ~[?:?]
	at me.armar.plugins.autorank.leaderboard.LeaderboardHandler.updateLeaderboard(LeaderboardHandler.java:401) ~[?:?]
	at me.armar.plugins.autorank.storage.StorageProvider$1.run(StorageProvider.java:175) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-f56e2e7-2aba349]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-f56e2e7-2aba349]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Thanks a lot.
With best regards Gartentrulla from Germany
