### ISSUE TITLE
change with Stats

### ISSUE THREAD

**Issue by Ghossst198** [Staartvin/Autorank-2#442]
Hi, I tried to use Stats plugin, but when I put it in server, it does lots of errors and even autorank is disabled, when I delete it, autorank is working but players cant promote because I have block broken in config, is there any other plugin like Statz that can be used with Autorank?? Please FAST!

**Comment by Staartvin** [comment]
What errors are you getting with Statz?

**Comment by Ghossst198** [comment]
Now it looks like working, but is there any command to see what it is counting? Player have 4 votes for next rank but in console: The Votes stat has been disabled due to issues with Votifier.

And I dont know if its counting other things like broken blocks etc.

**Comment by Staartvin** [comment]
You can see that by doing **/statz help** to see a list commands!

**Comment by Ghossst198** [comment]
No I cant, I have plugin Stats3 there is not command /statz

**Comment by Ghossst198** [comment]
That was previously plugin I had

**Comment by Staartvin** [comment]
Hmm, for Autorank you should be running Statz, not Stats 3. Stats 3 support is being removed from Autorank.

**Comment by Ghossst198** [comment]
But when I ran Statz, players didnt get promoted

**Comment by Ghossst198** [comment]
I was running older version of autorank, because when I do /ar check in last version, it does this 

`[2K [21:34:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.8.5.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-6016ac7-10c10b3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [server.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [server.jar:git-Spigot-6016ac7-10c10b3]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
at me.staartvin.statz.hooks.handlers.StatsAPIHandler.getNormalStat(StatsAPIHandler.java:164) ~[?:?]
at me.armar.plugins.autorank.statsmanager.handlers.StatsHandler.getNormalStat(StatsHandler.java:38) ~[?:?]
at me.armar.plugins.autorank.playerchecker.requirement.TotalVotesRequirement.meetsRequirement(TotalVotesRequirement.java:39) ~[?:?]
at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:79) ~[?:?]
at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:143) ~[?:?]
at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:283) ~[?:?]
at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:150) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-6016ac7-10c10b3]
... 15 more `

**Comment by Ghossst198** [comment]
Then it did this:
`Exception in thread "Craft Scheduler Thread - 51"
>[2K [21:35:14 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.5.1 generated an exception while executing task 5026
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at me.staartvin.statz.hooks.handlers.StatsAPIHandler.getNormalStat(StatsAPIHandler.java:164)
at me.armar.plugins.autorank.statsmanager.handlers.StatsHandler.getNormalStat(StatsHandler.java:38)
at me.armar.plugins.autorank.playerchecker.requirement.TotalVotesRequirement.meetsRequirement(TotalVotesRequirement.java:39)
at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:79)
at me.armar.plugins.autorank.rankbuilder.ChangeGroup.checkRequirements(ChangeGroup.java:150)
at me.armar.plugins.autorank.rankbuilder.ChangeGroup.applyChange(ChangeGroup.java:94)
at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:75)
at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:65)
at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:87)
at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more `

**Comment by cjburkey01** [comment]
I'm getting that `null` error.
