### ISSUE TITLE
Error Null on /ar check

### ISSUE THREAD

**Issue by cjburkey01** [Staartvin/Autorank-2#448]
Calling this command always throws this exception in the console, even if the user has a path:
```
[20:59:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v4.0.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.armar.plugins.autorank.config.PlayerDataConfig.getChosenPath(PlayerDataConfig.java:281) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathManager.getCurrentPath(PathManager.java:106) ~[?:?]
	at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:52) ~[?:?]
	at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:265) ~[?:?]
	at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:169) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-80dd971]
	... 15 more
```
I see quite a few other people having this problem, and none of them have been given a solution.

**Comment by Imothep80** [comment]
Hi,

get the same issue. But i found the Problem in the configuration of the path file. Can it be that you just have copy paste your old path to the new file?
