### ISSUE TITLE
internal error while running /ar reload

### ISSUE THREAD

**Issue by Ironic8b498** [Staartvin/Autorank-2#456]
At first I thought it was me not got the format right in my path.yml. I have deleted the folder and started my server up and I get an error in logs about the path.yml 

`[09:12:13] [Server thread/WARN]: [Autorank] Task #107 for Autorank v4.0.2 generated an exception
java.lang.IllegalArgumentException: Result 'rank change' of group 'Test' is unknown!
	at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:139) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:154) ~[?:?]
	at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:305) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

Which I believed it was unknown rank an world name, but it was wrong. NO errors at bootup if I get rid of rank change line. and /ar reload works. So back to my original thought what the problem was, a format issue in path.yml

**Comment by Staartvin** [comment]
The rank change result is temporarily disabled, see here: https://www.spigotmc.org/resources/autorank.3239/update?update=141924

**Comment by zerafox** [comment]
I'm running 4.0.2 of Autorank on my server and just edited the "Test" rank to be unrecognizable, to be sure I had the layout and format correct.
Once I saved and uploaded it to the server, I also get this exact error when I use /ar reload.
When checking the Paths.yml I'm noticing that "Test" is regenerated. I've already triple checked my parsing and it is correct. (I use notepad++ to tell me about TABs etc; As well as checking with [an online yaml parser](http://yaml-online-parser.appspot.com/))

Since this is my first time using AutoRank, I've used the wiki for every step of the way and the only error I'm ever getting is for this auto-generated example that keeps reappearing. :\

**Comment by Staartvin** [comment]
The error is related to the test path. Try stopping the server, removing the test path and restarting the server.

**Comment by zerafox** [comment]
That allowed me to delete the Test path, thank you. :)

I am eager to give this a go, it looks like it can meet any need I'd ever need when it comes to meeting requirements. :) Thank you!

**Comment by Staartvin** [comment]
Glad to hear you got it working! If you ever run into trouble,  don't hesitate to ask them here!

**Comment by Ironic8b498** [comment]
Wish I noticed the rank change being disabled when I read the change log, before I spent all day trying to figure this out. heres what I got on my path.yml file just need to know if I have any errors since I use numbers for my ranks.
[Paths .yml.txt](https://github.com/Staartvin/Autorank-2/files/752756/Paths.yml.txt)

**Comment by zerafox** [comment]
I personally felt more comfortable basing it off permission nodes myself.
Granting a node per group and taking it away in the next one. >.>
I assumed the 'group' was part of the rank change feature, and honestly I'm
used to using nodes to allow/deny access to things globally anyway.
