### ISSUE TITLE
Autorank config issues

### ISSUE THREAD

**Issue by DiscrafT** [Staartvin/Autorank-2#468]
Hello I was recently adding some new ranks to my server using AutoRank advanced config. But after i upload it and reload AR plugin does not work anymore. Can somebody find out what is wrong with it?I wan't to start after login as Rolnik (that means farmer) and after 120 played hours end as pretorian.
Thank you so much.
CONSOLE ERROR: 

[18:45:38 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.7.2 generated an exception while executing task 225753
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:88)
at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:91)
at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:56)
at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:65)
at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:84)
at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

[REMOVED CONFIGS]

**Comment by DiscrafT** [comment]
Config files:


[configs.zip](https://github.com/Staartvin/Autorank-2/files/764559/configs.zip)

**Comment by Staartvin** [comment]
Unfortunately, I cannot provide much support to much older version. Please think about upgrading to Autorank 4.

**Comment by DiscrafT** [comment]
In my opinion is autorank 4 much more complicated but i will try to upgrade it.
