### ISSUE TITLE
[WARNING] [Autorank] Task #81 for Autorank v4.0.5 generated an exception

### ISSUE THREAD

**Issue by ardentcrest** [Staartvin/Autorank-2#482]
00:05:01 [WARNING] [Autorank] Task #81 for Autorank v4.0.5 generated an exception
00:05:01 java.lang.NullPointerException
00:05:01 	at me.armar.plugins.autorank.config.PathsConfig.getResults(PathsConfig.java:390) ~[?:?]
00:05:01 	at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:139) ~[?:?]
00:05:01 	at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:154) ~[?:?]
00:05:01 	at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:326) ~[?:?]
00:05:01 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
00:05:01 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
00:05:01 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
00:05:01 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
00:05:01 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
00:05:01 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
00:05:01 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by ardentcrest** [comment]
Fixed
