### ISSUE TITLE
A helpful hand is required.

### ISSUE THREAD

**Issue by 8eeved** [Staartvin/Autorank-2#496]
Please forgive me if I have posted this in the incorrect place, and please delete if so.

I'm running a spigot server with MC v1.11, Autorank 4.0.5 and Statz 1.4.3
I have been toiling over this error for the past few days and finally decided I needed to get some help before I pull whats remaining of my hair, out. Any help that can be offered would be appreciated and much respect offered in return.

**To begin with here is the error message I'm confronted with:**

[01:17:54 INFO]: [Autorank] Found Statz plugin: Statz (by Staartvin)

[01:17:54 INFO]: [Autorank] Hooked into Statz (by Staartvin)

[01:17:54 INFO]: [Autorank] Loaded libraries and dependencies

[01:17:54 WARN]: [Autorank] Task #75 for Autorank v4.0.5 generated an exception

java.lang.NullPointerException

	at me.armar.plugins.autorank.config.PathsConfig.getResults(PathsConfig.java:390) ~[?:?]

	at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:139) ~[?:?]

	at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:154) ~[?:?]

	at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:326) ~[?:?]

	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-b605b31-91c3152]

	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-b605b31-91c3152]

	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-b605b31-91c3152]

	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-b605b31-91c3152]

	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-b605b31-91c3152]

	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-b605b31-91c3152]

	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

and this is what the "paths" file contains:

ranks:
    Peasant:
        requirements:
            time:
                 value: 25h
        results:
            rank change: Peasant;Reeve
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Reeve!'
            message: 'Congratulations, you are now a Reeve.'
    Reeve:
        requirements:
            blocks moved: 1000		
            blocks broken: 1;500
            votes: 15			
            time:
                value: 4d
            exp:
                value: 45
            jobs current points:
                value: 15
            has item:
                value: 351;12;coco bean
            has item2:
                value: 288;25;feather
            mobs killed:
                value: 15;pig
            mobs killed2:
                value: 20;spider
        results:
            rank change: Reeve;Squire
            command: 'say &p has just been promoted to Squire!; give &p 15 264; tell &p You have just earned 15 Diamonds!'
            message: 'Congratulations, you are now a Squire.'
   
The file continues, and is a duplicate of the above with each rank added in its own right, therefore I feel it wasn't warranted posting the rest, I checked the .yml on-line for errors and it passed successfully, therefore I'm surmising I have made an error in the code I have entered, and that's why I'm here. My knowledge is limited and those that browse here far out gun me.
Thanking you in advance,

Cheers, DV.

**Comment by Staartvin** [comment]
Could you post this part of your paths file in pastebin.com? That's easier to read as this automatically formats text incorrectly.

**Comment by 8eeved** [comment]
Thank you for your speedy response,Staartvin.
I have followed your advice and posted the file on pastebin.
