### ISSUE TITLE
Autorank group error that is unknown

### ISSUE THREAD

**Issue by zippyx17** [Staartvin/Autorank-2#498]
I have this error and I can't figure out what I've done wrong:
----------
```
09.04 11:42:24 [Server] INFO ... 3 more
09.04 11:42:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
09.04 11:42:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
09.04 11:42:24 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
09.04 11:42:24 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:85)
09.04 11:42:24 [Server] INFO at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:63)
09.04 11:42:24 [Server] INFO at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:54)
09.04 11:42:24 [Server] INFO at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:95)
09.04 11:42:24 [Server] INFO at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:99)
09.04 11:42:24 [Server] INFO Caused by: java.lang.NullPointerException
09.04 11:42:24 [Server] INFO at java.lang.Thread.run(Unknown Source)
09.04 11:42:24 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
09.04 11:42:24 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
09.04 11:42:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
09.04 11:42:24 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.4 generated an exception while executing task 7966
09.04 11:42:24 [Server] WARN Exception in thread "Craft Scheduler Thread - 7" 
09.04 11:42:22 [Server] INFO Players: [Moderator] Apollo, [Owner/Dev] Neptunide
09.04 11:42:18 [Multicraft] SPAS24 ran command Message of the Day
09.04 11:42:18 [Server] INFO ... 3 more
09.04 11:42:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
09.04 11:42:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
09.04 11:42:18 [Server] INFO at me.armar.plugins.autorank.listeners.PlayerJoinListener$1.run(PlayerJoinListener.java:54)
09.04 11:42:18 [Server] INFO at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:54)
09.04 11:42:18 [Server] INFO at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:95)
09.04 11:42:18 [Server] INFO at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:99)
09.04 11:42:18 [Server] INFO Caused by: java.lang.NullPointerException
09.04 11:42:18 [Server] INFO at java.lang.Thread.run(Unknown Source)
09.04 11:42:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
09.04 11:42:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
09.04 11:42:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
09.04 11:42:18 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.4 generated an exception while executing task 9950
09.04 11:42:18 [Server] WARN Exception in thread "Craft Scheduler Thread - 17" 
```
------------------

Removed config files.. [by Staartvin]

**Comment by Staartvin** [comment]
Please paste your files in pastebin.com, since this is impossible to read.

**Comment by zippyx17** [comment]
Sorry about that. Here it is: https://pastebin.com/8sBjPgdQ

**Comment by Staartvin** [comment]
It seems like your files are formatted incorrectly.

**Comment by zippyx17** [comment]
It's just that the spaces didn't get put in when I copy/pasted. But I have them spaced correctly.
