### ISSUE TITLE
Task #38 generated an exception (at startup)

### ISSUE THREAD

**Issue by jeffm13** [Staartvin/Autorank-2#534]
[13:39:47] [Server thread/WARN]: [Autorank] Task #38 for Autorank v4.0.7 generated an exception
java.lang.NullPointerException: null
	at me.armar.plugins.autorank.config.PathsConfig.getResults(PathsConfig.java:277) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:42) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:151) ~[?:?]
	at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:310) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

**Comment by Staartvin** [comment]
Can you show me your paths file?

**Comment by jeffm13** [comment]
```
# Paths file - This file will contain all paths that a player is allowed to take. Previously known as 'AdvancedConfig.yml'.
# This file contains (by default) a Test group that shows the basic syntax of this file. 
# For more information, go to https://github.com/Armarr/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F.


#############################################################################
#                                                                           #
#                   Autorank Simple Config                                  #
#                                                                           #
#############################################################################

# The format for rank changes is
#   rank1: rank2 after 1d 1h 1m
# where rank1 is the player's current rank
# and rank2 is the rank the player will get after the set time
# 1d = 1 day
# 1h = 1 hour
# 1m = 1 minute

# guest: member after 1h
# member: vip after 5d

starter: noob after 1h
fighter: starter after 2h
stealthy: fighter after 2h
warrior: stealthy after 3h
admiral: warrior after 5h
commander: admiral after 8h
hero: commander after 12h
legendary: hero after 40h

```

**Comment by Staartvin** [comment]
Hmm, this is the SimpleConfig that is not being used anymore. Are you using the paths.yml file?
