### ISSUE TITLE
Autorank not working for /ar or hardly any of the commands!

### ISSUE THREAD

**Issue by dillonk01** [Staartvin/Autorank-2#535]
[13:10:10 WARN]: Unexpected exception while parsing console command "ar"
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v4.0.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-963b19c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-963b19c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:627) ~[craftbukkit.jar:git-Bukkit-963b19c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:613) [craftbukkit.jar:git-Bukkit-963b19c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:408) [craftbukkit.jar:git-Bukkit-963b19c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:372) [craftbukkit.jar:git-Bukkit-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit.jar:git-Bukkit-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit.jar:git-Bukkit-963b19c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:144) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-963b19c]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-963b19c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-963b19c]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:144) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-963b19c]
        ... 8 more

Debug File:
This is a debug file of Autorank. You should give this to an author or ticket manager of Autorank.
You can go to http://pastebin.com/ and paste this file. Then, give the link and state the problems you're having in a ticket on the Autorank page.

Date created: 2017-08-16 13:09:39

Autorank version: 4.0.7

Server implementation: git-Bukkit-963b19c (MC: 1.12.1)

Server version: 1.12.1-R0.1-SNAPSHOT

Server warning state: DEFAULT

Ranks defined: 

 ------------------- Path debug info ------------------- 
Path: Test
Display name: Test path
Prerequisites: 
    1. Be in world_nether
    2. Have at least 1000.0 Reais
Requirements: 
    1. Have at least 10000.0 Reais
    2. Break at least 50 blocks
Results: 
    1. Perform the following command(s): §7broadcast &p has just completed path 'Default'!§r
    2. Perform the following command(s): §7give &p 1 100§r
    3. Perform the following command(s): §7pex user &p group set Default§r
    4. Send you the following message: Congratulations, you completed the 'Default' path!
----------------------------

Using MySQL: false

Java version: 1.8.0_144

Operating system: Windows 10

OS version: 10.0

OS architecture: x86

Loaded addons: []

**Comment by dillonk01** [comment]
Keep in mind also that I haven't touched any of the settings yet... so it could be Statz or something else along with it..

**Comment by Staartvin** [comment]
Thanks for the info! That's quite a big output. The error seems to suggest you're running a exotic server implementation? What server software are you running? Bukkit, Spigot, Sponge?

**Comment by Staartvin** [comment]
Also note that Autorank 4.0.7 does not work with MC 1.12 yet

**Comment by dillonk01** [comment]
Ah okay. Sorry for the late response, but I'm on Bukkit 1.12.1. I'm a little noobish to the servers and plugins thing. Just testing one on my computer. Thanks for the response!
