### ISSUE TITLE
Autorank v4.0.7 generated an exception while executing task 69

### ISSUE THREAD

**Issue by hasanas83V2001** [Staartvin/Autorank-2#539]
`[08:49:21 WARN]: [Autorank] Plugin Autorank v4.0.7 generated an exception while executing task 69
java.lang.NullPointerException: null
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:119) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:135) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:145) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:145) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:145) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:298) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:236) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at me.armar.plugins.autorank.config.SimpleYamlConfiguration.saveFile(SimpleYamlConfiguration.java:94) ~[?:?]
        at me.armar.plugins.autorank.config.InternalPropertiesConfig.setCachedLeaderboard(InternalPropertiesConfig.java:156) ~[?:?]
        at me.armar.plugins.autorank.leaderboard.LeaderboardHandler.updateLeaderboard(LeaderboardHandler.java:402) ~[?:?]
        at me.armar.plugins.autorank.leaderboard.LeaderboardHandler$4.run(LeaderboardHandler.java:317) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

**Comment by frizzbee30** [comment]
probably totally unrelated, but have you run your files through a yaml parser ?
