### ISSUE TITLE
MySQL 5.7 issues

### ISSUE THREAD

**Issue by Tkopic001** [Staartvin/Autorank-2#555]
There's an issue with the new versions of MySQL 
The plugin refuses to connect to the server.

You're gonna need to add this parameter while connecting to the database:

useSSL=false

Since my MySQL server has no SSL certificates it can't provide an SSL connection

Some info:
mysql: 
Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper

minecraft server:
 ver  git-Bukkit-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Thanks!

**Comment by Tkopic001** [comment]
Here's an error from the logs:

[07:24:18] [Server thread/ERROR]: Error occurred while disabling Autorank v3.8.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at me.armar.plugins.autorank.mysql.wrapper.MySQLWrapper.disconnectDatabase(MySQLWrapper.java:330) ~[?:?]
        at me.armar.plugins.autorank.Autorank.onDisable(Autorank.java:172) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:353) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:416) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:339) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:454) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:586) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        ... 10 more

**Comment by Tkopic001** [comment]
Sorry false alarm
