### ISSUE TITLE
Autorank v3.8.5.1 generated an exception while executing task 40

### ISSUE THREAD

**Issue by Jager67** [Staartvin/Autorank-2#561]
[04:31:56] [Craft Scheduler Thread - 55/WARN]: Exception in thread "Craft Scheduler Thread - 55" 
[04:31:56] [Craft Scheduler Thread - 55/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.5.1 generated an exception while executing task 40
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at me.armar.plugins.autorank.config.ConfigHandler.getResults(ConfigHandler.java:178)
	at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initAdvancedConfig(ChangeGroupBuilder.java:239)
	at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initialiseChangeGroups(ChangeGroupBuilder.java:52)
	at me.armar.plugins.autorank.rankbuilder.ChangeGroupManager.initialiseFromConfigs(ChangeGroupManager.java:47)
	at me.armar.plugins.autorank.Autorank$2.run(Autorank.java:337)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Staartvin** [comment]
Can you provide your paths file?

**Comment by Jager67** [comment]
Paths file - This file will contain all paths that a player is allowed to take. Previously known as 'AdvancedConfig.yml 

Didn't see that it replaced AdvacedConfig.yml so Paths file is default I'll start working on it thanks.

**Comment by Jager67** [comment]
Ok I've setup the Paths.yml file an I still got the same issue it seems.

https://pastebin.com/1NJUu38Y

Here is my Latest Log file.

https://pastebin.com/i3LSVAwU
