### ISSUE TITLE
Could not load too :(

### ISSUE THREAD

**Issue by M4rtyn4** [Staartvin/Autorank-2#572]
`
[23:48:36] [Server thread/ERROR]: Could not load 'plugins\Autorank-4.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PluginLibrary
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-549c1fa-2ee49b4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[23:48:38] [Server thread/INFO]: [MinePacks] Loading MinePacks v1.17.6
`

**Comment by Kuouo** [comment]
Download PluginLibrary and add it to your plugins server. Restart the server.

**Comment by M4rtyn4** [comment]
Thanks :D
