### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by Drhampust** [Staartvin/Autorank-2#578]
I have now made groups (dont actuly know if the gruops are valid in PEX and have configured the AutoRank for the groups but it gives me a ton of warnings and in game a error that the comman donsent work.
[Ny(tt) WinRAR ZIP archive.zip](https://github.com/Staartvin/Autorank-2/files/1628768/Ny.tt.WinRAR.ZIP.archive.zip)
server log PEX groups and Path File for AutoRank

**Comment by Drhampust** [comment]
> [23:01:28 INFO]: Hampus_Toft issued server command: /ar check
[23:01:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v4.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628) ~[craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1338) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1198) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.pathbuilder.requirement.GroupRequirement.meetsRequirement(GroupRequirement.java:40) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:257) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.Path.meetsPrerequisites(Path.java:250) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathManager.getPossiblePaths(PathManager.java:135) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathManager.autoAssignPath(PathManager.java:263) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:53) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:223) ~[?:?]
        at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:137) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        ... 15 more

> [23:04:34 WARN]: [Autorank] Plugin Autorank v4.1 generated an exception while executing task 119
java.lang.NullPointerException: null
        at me.armar.plugins.autorank.pathbuilder.requirement.GroupRequirement.meetsRequirement(GroupRequirement.java:40) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:257) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.Path.meetsPrerequisites(Path.java:250) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathManager.getPossiblePaths(PathManager.java:135) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathManager.autoAssignPath(PathManager.java:263) ~[?:?]
        at me.armar.plugins.autorank.data.flatfile.UpdatePlaytime.updateMinutesPlayed(UpdatePlaytime.java:99) ~[?:?]
        at me.armar.plugins.autorank.data.flatfile.UpdatePlaytime.updateMinutesPlayed(UpdatePlaytime.java:55) ~[?:?]
        at me.armar.plugins.autorank.data.flatfile.UpdatePlaytime.run(UpdatePlaytime.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit-1.12.2.jar:git-Bukkit-bd30843]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
