### ISSUE TITLE
Just a random error on boot

### ISSUE THREAD

**Issue by RainOfPain125** [Staartvin/Autorank-2#592]
[02:31:30 WARN]: [Autorank] Task #168 for Autorank v4.1 generated an exception
java.lang.NullPointerException: null
        at me.armar.plugins.autorank.config.PathsConfig.getRequirements(PathsConfig.java:198) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:83) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:151) ~[?:?]
        at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:259) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1320]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1320]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1320]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1320]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1320]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1320]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

git-Paper-1320
 Plugins (72): AreaShop, ArrowTrails, Auctions, Autorank, AutoSaveWorld, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, DailyBonus, DeluxeJoin, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FactionsFly, HolographicDisplays, HolographicScoreboard, InfoBook, InventoryFull, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, MobArena, Multiverse-Core, NoCheatPlus, NoPlugins, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PlayTime, PluginLibrary, PowerNBT, ProtocolLib, React, ServerListPlus, ShopChest, ShopGUIPlus, ShulkerBlock, SilkSpawners, SilkSpawnersShopAddon, SimpleBackup, StopProxy, SuperbVote, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, Vault, Votifier, WarningCategories, Wild, WorldBorder, WorldEdit, WorldGuard

**Comment by vapecloudbear** [comment]
Should be a syntax error in one of your config files. Copy and Paste the config files contents here separately and verify they are correct. https://codebeautify.org/yaml-validator

**Comment by RainOfPain125** [comment]
Can't be that, unless the plugin CAME with invalid YML, because thats what this websites saying - things I didn't edit is "invalid" YML

Heres my configs -
https://pastebin.com/Y1vgKGVF
https://pastebin.com/YDq5fPW9

**Comment by vapecloudbear** [comment]
I’m not 100% sure here, just trying to help, but it is possible that the paths file require a prerequisite. See here. https://github.com/Staartvin/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F  To test, you could just put in prerequisites: in group: value: default

**Comment by RainOfPain125** [comment]
Is there a way to have no pre-requisites? I just wanted AutoRank to automatically give people with a certan amount of hours an "experienced" / "veteran" rank and thats about it. I deleted the requisites section

**Comment by vapecloudbear** [comment]
I don’t know. Do you only have 2 ranks on the server currently?

**Comment by RainOfPain125** [comment]
Only that one

**Comment by Staartvin** [comment]
Try to update to Autorank v4.2.3. Paths without prerequisites will be supported in the next version.
