### ISSUE TITLE
Error : Task 241 for AutoRank Dev 34

### ISSUE THREAD

**Issue by TheIntelloBox** [Staartvin/Autorank-2#605]
[19:40:09] [Server thread/INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[19:40:09] [Server thread/INFO]: [Autorank] Loaded libraries and dependencies
[19:40:09] [Server thread/ERROR]: [Autorank] Could not hook into a dependency: 
Cause: null
[19:40:09] [Server thread/WARN]: [Autorank] Task #241 for Autorank v4.1-Dev-34 generated an exception
java.lang.NullPointerException: null
	at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:41) ~[Autorank-4.1-Dev-34.jar:?]
	at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[Autorank-4.1-Dev-34.jar:?]
	at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:261) ~[Autorank-4.1-Dev-34.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1329]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Staartvin** [comment]
Try this version: http://178.62.255.148:8080/job/Autorank/48/
