### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by Patatone** [Staartvin/Autorank-2#620]
[Autorank] Task #95 for Autorank v4.1 generated an exception
java.lang.NullPointerException: null
	at me.armar.plugins.autorank.config.PathsConfig.getRequirements(PathsConfig.java:198) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:54) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:151) ~[?:?]
	at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:259) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1391]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1391]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1391]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Staartvin** [comment]
Can you show me your paths file?

**Comment by Patatone** [comment]
![image](https://user-images.githubusercontent.com/34103646/38795738-7a2834ea-4159-11e8-862c-8c822a5bbdff.png)

**Comment by Staartvin** [comment]
I meant the file itself, what is inside the file. How did you configure it?

**Comment by Patatone** [comment]
Settings: https://hastebin.com/ociwebahut.coffeescript
Paths: https://hastebin.com/juseqezefo.cs
internalprops: https://hastebin.com/likuqiwugi.erl

**Comment by Staartvin** [comment]
Your 'utente' path does not have any requirements, that is not possible.

**Comment by Patatone** [comment]
It's the start point

**Comment by Staartvin** [comment]
If you want users to be a in a certain permission group when they start, you can set this in your permissions plugin. Autorank requires every path to have at least one requirement.
