### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by dalgrim** [Staartvin/Autorank-2#622]
The following error is thrown on server startup:

[09:38:30 WARN]: [Autorank] Task #49 for Autorank v4.1 generated an exception
java.lang.NullPointerException: null
        at me.armar.plugins.autorank.config.PathsConfig.getRequirements(PathsConfig.java:198) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathBuilder.initialisePaths(PathBuilder.java:83) ~[?:?]
        at me.armar.plugins.autorank.pathbuilder.PathManager.initialiseFromConfigs(PathManager.java:151) ~[?:?]
        at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:259) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Autorank is not keeping time either I'll post a separate issue as they may not be related

**Comment by Staartvin** [comment]
Can you show me your paths file?

**Comment by dalgrim** [comment]
Visitor to Member:
    prerequisites:
        in group:
            value: Visitor
    requirements:
        global time: 60m
    results:
        command: 'pp user &p setgroup Member'
        message: 'Congratulations &p, you are now a Member'
    options:
        display name: Member
        auto choose: true

**Comment by dalgrim** [comment]
update: I restarted and now I get these errors:
```
[16:43:08 ERROR]: [Autorank] Could not hook into a dependency:
Cause: com/github/cheesesoftware/PowerfulPermsAPI/PowerfulPermsPlugin
[16:43:08 WARN]: [Autorank] Task #49 for Autorank v4.1 generated an exception
java.lang.NullPointerException: null
        at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:40) ~[?:?]
        at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[?:?]
        at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:262) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.jar:git-Spigot-eadd615-9060bfa]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

```

**Comment by Staartvin** [comment]
Can you try this version: http://178.62.255.148:8080/job/Autorank/48/
