### ISSUE TITLE
Task #72 for Autorank v4.2 generated an exception

### ISSUE THREAD

**Issue by M4rtyn4** [Staartvin/Autorank-2#624]
`
[14:20:06] [Server thread/INFO]: [Autorank] Loaded libraries and dependencies
[14:20:06] [Server thread/ERROR]: [Autorank] Could not hook into a dependency: 
Cause: null
[14:20:06] [Server thread/WARN]: [Autorank] Task #72 for Autorank v4.2 generated an exception
java.lang.NullPointerException: null
	at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:41) ~[?:?]
	at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[?:?]
	at me.armar.plugins.autorank.Autorank$2.run(Autorank.java:290) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]`

Hi I am getting this error on start up. What should I do?

**Comment by M4rtyn4** [comment]
I also get this error when I log in.
`[14:34:21] [Server thread/INFO]: M4rtyn4[/92.233.42.73:50931] logged in with entity id 535 at ([world]-211.07349350621655, 43.0625, -595.8091766057677)
[14:34:21] [Craft Scheduler Thread - 28/WARN]: [Autorank] Plugin Autorank v4.2 generated an exception while executing task 165
java.lang.NullPointerException: null
	at me.armar.plugins.autorank.pathbuilder.requirement.InGroupRequirement.meetsRequirement(InGroupRequirement.java:38) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:263) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.Path.meetsPrerequisites(Path.java:249) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathManager.getPossiblePaths(PathManager.java:134) ~[?:?]
	at me.armar.plugins.autorank.pathbuilder.PathManager.autoAssignPath(PathManager.java:262) ~[?:?]
	at me.armar.plugins.autorank.listeners.PlayerJoinListener$1.run(PlayerJoinListener.java:42) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
`

**Comment by Staartvin** [comment]
Hmm, can you show me your paths.yml file?

**Comment by M4rtyn4** [comment]
Here it is:
[https://pastebin.com/eCgh7Yyt](url)
It is the same since 4.1 version. 
Error Started when I updated to 4.2 and I also updated PluginLibrary to 1.2.
Now I downloaded Autorank4.2.1

**Comment by M4rtyn4** [comment]
I added them here:
`
  prerequisites:
    in group:
      value: '1'`
And it changed from task 72 to 71
`
[14:22:59 ERROR]: [Autorank] Could not hook into a dependency:
Cause: null
[14:22:59 WARN]: [Autorank] Task #71 for Autorank v4.2.1 generated an exception
java.lang.NullPointerException: null
        at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:41) ~[?:?]
        at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[?:?]
        at me.armar.plugins.autorank.Autorank$2.run(Autorank.java:290) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]`

I tried to add '' here too:
`
  prerequisites:
    in group:
      value: 'VIP'`
Just in case but same error.

**Comment by M4rtyn4** [comment]
I run it on new server without so it can create its own folder and same thing but different task error
`
[14:42:51 WARN]: [Autorank] Task #75 for Autorank v4.2.1 generated an exception
java.lang.NullPointerException: null
        at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:41) ~[?:?]
        at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[?:?]
        at me.armar.plugins.autorank.Autorank$2.run(Autorank.java:290) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]`

**Comment by Staartvin** [comment]
Try this version: http://178.62.255.148:8080/job/Autorank/48/

**Comment by M4rtyn4** [comment]
Perfect! Thank You.
