### ISSUE TITLE
Cause Error: Null (v4.2.1)

### ISSUE THREAD

**Issue by DrFallen** [Staartvin/Autorank-2#627]
[12:40:59 WARN]: [Autorank] Task #75 for Autorank v4.2.1 generated an exception
java.lang.NullPointerException: null
at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:41) ~[?:?]
at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[?:?]
at me.armar.plugins.autorank.Autorank$2.run(Autorank.java:290) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-2086bb0-21d5f75]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-2086bb0-21d5f75]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-2086bb0-21d5f75]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Seem to be getting this issue with the plugin posted Thursday 26th. Both PluginLibrary and Statz are running latest version.

**Comment by Staartvin** [comment]
Thanks for reporting it. Many people have reported this issue and hence many different tickets on this tracker are made. I'll close this issue as it is a duplicate, but please watch a ticket with your issue to see if it is resolved.

**Comment by Staartvin** [comment]
Wait, before I close, does this version solve the issue: http://178.62.255.148:8080/job/Autorank/48/

**Comment by DrFallen** [comment]
I've updated it to the dev version linked above and it seems to of removed the error.

**Comment by Staartvin** [comment]
Very nice. You can upgrade to Autorank 4.2.3 to get the latest stable version that includes that fix. I'll close the issue now.
