### ISSUE TITLE
3.7.1 to 4.2.1 problem.

### ISSUE THREAD

**Issue by Fix3dll** [Staartvin/Autorank-2#628]
[16:25:54 INFO]: [PluginLibrary] Enabling PluginLibrary v1.2-Dev-38
[16:25:54 INFO]: [PluginLibrary] ***== Loading libraries ==***
[16:25:54 INFO]: [PluginLibrary] ***== Loaded 4 libraries! ==***
[16:25:54 INFO]: [PluginLibrary] Loaded libraries: ASkyBlock (by tastybento), Vault (by Kainzo), WorldGuard (by sk89q) and EssentialsX (by drtshock)
[16:25:54 INFO]: [PluginLibrary] *** Ready for plugins to send/retrieve data. ***
[16:25:54 INFO]: [PluginLibrary] PluginLibrary v1.2-Dev-38 is now enabled!
[16:25:54 INFO]: [Autorank] Enabling Autorank v4.2.2
[16:25:54 INFO]: [Autorank] Interval check every 5 minutes.
[16:25:54 INFO]: [Autorank] Primary storage provider of Autorank: FlatFileStorageProvider
[16:25:54 INFO]: [Autorank] Using timings of: autorank
[16:25:54 INFO]: [Autorank] Since this is the first time running Autorank 3.7.1, I need to convert your UUID files to a new format.
[16:25:54 INFO]: [Autorank] Converting UUID files to new format (3.7.1), this may take a while.
[16:25:54 ERROR]: Error occurred while enabling Autorank v4.2.2 (Is it up to date?)
java.lang.NullPointerException
        at me.armar.plugins.autorank.util.uuid.storage.UUIDStorage.transferUUIDs(UUIDStorage.java:339) ~[?:?]
        at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:357) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[16:25:54 INFO]: [Autorank] Disabling Autorank v4.2.2
[16:25:54 INFO]: [Autorank] Autorank 4.2.2 has been disabled!
I am using first time this plugin?! I didnt use 3.7.1

**Comment by Staartvin** [comment]
Generally, this is not a big issue. I've put a new version that fixes this issue: http://178.62.255.148:8080/job/Autorank/47/

**Comment by Fix3dll** [comment]
@Staartvin `[17:02:35 INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[17:02:35 INFO]: [Autorank] Loaded libraries and dependencies
[17:02:35 ERROR]: [Autorank] AbstractRequirement 'blocks broken' relies on 'Statz' being installed, but that plugin is not installed!
[17:02:35 WARN]: [Autorank] Task #88 for Autorank v4.2.2-Dev-47 generated an exception
java.lang.NullPointerException
        at me.armar.plugins.autorank.permissions.handlers.LuckPermsHandler.getGroups(LuckPermsHandler.java:84) ~[?:?]
        at me.armar.plugins.autorank.validations.ValidateHandler.validatePermGroups(ValidateHandler.java:42) ~[?:?]
        at me.armar.plugins.autorank.validations.ValidateHandler.startValidation(ValidateHandler.java:25) ~[?:?]
        at me.armar.plugins.autorank.Autorank$2.run(Autorank.java:291) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

**Comment by Staartvin** [comment]
Can you try this version: http://178.62.255.148:8080/job/Autorank/48/
