### ISSUE TITLE
Mobs Killed requirement not working

### ISSUE THREAD

**Issue by coletam** [Staartvin/Autorank-2#633]
Hello,

Currently using the latest version of AutoRank and the necessary dependencies (plus Statz) on 1.12.2 PaperSpigot. It seems that the mobs-killed requirement doesn't work. Adding that as a requirement gives an internal error message upon using the /autorank check command. Removing the requirement fixes the issue. The error is posted below. 

Example of the path / requirement:
> RANK-NAME:
>   prerequisites:
>     in group: PREV-RANK-NAME
>   requirements:
>     time: 36h
>     money: 7500
>     exp: 50
>     battlelevels kills: 12
>     mobs killed: 100;zombie
>   results:
>     command: pex promote &p normal

**Error in Hastebin:** https://hastebin.com/deganefiqi.vbs
**ERROR:**
> 13.05 02:12:58 [Server] ERROR null
> 13.05 02:12:58 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'autorank' in plugin Autorank v4.2.3
> 13.05 02:12:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:37) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
> 13.05 02:12:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1415]
> 13.05 02:12:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
> 13.05 02:12:58 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/staartvin/statz/datamanager/player/PlayerStat
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.hooks.statzapi.StatzAPIHandler.getSpecificData(StatzAPIHandler.java:75) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.statsmanager.handlers.StatzHandler.getNormalStat(StatzHandler.java:51) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.pathbuilder.requirement.MobKillsRequirement.meetsRequirement(MobKillsRequirement.java:56) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.pathbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:263) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.playerchecker.PlayerChecker.getMetRequirementsHolders(PlayerChecker.java:197) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.playerchecker.PlayerChecker.getCompletedRequirementsHolders(PlayerChecker.java:158) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:143) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:212) ~[?:?]
> 13.05 02:12:58 [Server] INFO at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:120) ~[?:?]
> 13.05 02:12:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1415]

**Comment by coletam** [comment]
Oh right, I forgot I was using an older version of Statz. The reason why I downgraded from the latest version of Statz was because the playtime kept bugging out for some reason. Times were either rolling back when a player died or it'd reach to a certain point, then go back to 0 and repeat. 

I wasn't sure what the exact issue was, so I downgraded to 1.4.5 to see if it was maybe a bug in the newest version. I'll try the newest version again to fix the original post's issue.
