### ISSUE TITLE
Error with /ar check <track>

### ISSUE THREAD

**Issue by BloodshotPico** [Staartvin/Autorank-2#685]
`Thargha issued server command: /ar check The Beginning!
Server thread/ERROR 03:09:20
null
Console 03:09:20
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v4.2.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.LinkageError: me/staartvin/statz/database/datatype/RowRequirement
at me.armar.plugins.autorank.statsmanager.handlers.StatzHandler.getNormalStat(StatzHandler.java:61) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.pathbuilder.requirement.BlocksBrokenRequirement.meetsRequirement(BlocksBrokenRequirement.java:75) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.pathbuilder.holders.CompositeRequirement.meetsRequirement(CompositeRequirement.java:255) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.pathbuilder.Path.meetsAllRequirements(Path.java:299) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.pathbuilder.Path.checkPathProgress(Path.java:143) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:51) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.commands.CheckCommand.showSpecificPath(CheckCommand.java:83) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:202) ~[Autorank-4.2.6.jar:?]
at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:121) ~[Autorank-4.2.6.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-e5b1b5d-e5e8eec]
... 17 more`

**Comment by Staartvin** [comment]
Could you upgrade to the latest version of Autorank to see if it is fixed?
