### ISSUE TITLE
Issue with leaderboard on Autorank v4.3

### ISSUE THREAD

**Issue by Staartvin** [Staartvin/Autorank-2#702]
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]: Caused by: java.lang.NullPointerException
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.storage.mysql.CachedEntry.getCachedTime(CacheManager.java:109)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.storage.mysql.CacheManager.getCachedTime(CacheManager.java:52)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.storage.mysql.MySQLStorageProvider.lambda$getPlayerTime$3(MySQLStorageProvider.java:114)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     ... 6 more
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.leaderboard.LeaderboardHandler.getSortedTimesByUUID(LeaderboardHandler.java:183)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.leaderboard.LeaderboardHandler.lambda$getSortedLeaderboard$0(LeaderboardHandler.java:460)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]: Caused by: java.lang.NullPointerException
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.storage.mysql.CachedEntry.getCachedTime(CacheManager.java:109)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.storage.mysql.CacheManager.getCachedTime(CacheManager.java:52)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     at me.armar.plugins.autorank.storage.mysql.MySQLStorageProvider.lambda$getPlayerTime$3(MySQLStorageProvider.java:114)
[15:56:42] [ForkJoinPool.commonPool-worker-5/WARN]:     ... 6 more

**Comment by Staartvin** [comment]
Solved in dev build.
