### ISSUE TITLE
Trouble connecting with Quests (HappyPikachu)

### ISSUE THREAD

**Issue by JpCuber** [Staartvin/Autorank-2#720]
Hello, currently the Quests plugin and AutoRank are not talking properly and it is causing an error when checking for a player's rankup requirements. The requirement to complete the quest shows up in /ar view (rank) however when you do /ar check (rank) it does not show in the requirements you need yet and it gives you the error:
```
[23:19:19] [Craft Scheduler Thread - 33/WARN]: [Autorank] Plugin Autorank v4.3.3 generated an exception while executing task 4928
java.lang.NullPointerException: null
at me.staartvin.plugins.pluginlibrary.hooks.QuestsHook.getQuester(QuestsHook.java:57) ~[?:?]
at me.staartvin.plugins.pluginlibrary.hooks.QuestsHook.isQuestCompleted(QuestsHook.java:120) ~[?:?]
at me.armar.plugins.autorank.pathbuilder.requirement.QuestsCompleteSpecificQuestRequirement.meetsRequirement(QuestsCompleteSpecificQuestRequirement.java:30) ~[?:?]
at me.armar.plugins.autorank.pathbuilder.requirement.AbstractRequirement.isMet(AbstractRequirement.java:199) ~[?:?]
at me.armar.plugins.autorank.pathbuilder.holders.CompositeRequirement.meetsRequirement(CompositeRequirement.java:281) ~[?:?]
at me.armar.plugins.autorank.pathbuilder.Path.meetsAllRequirements(Path.java:303) ~[?:?]
at me.armar.plugins.autorank.pathbuilder.Path.checkPathProgress(Path.java:147) ~[?:?]
at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:53) ~[?:?]
at me.armar.plugins.autorank.listeners.PlayerJoinListener.lambda$onPlayerJoin$0(PlayerJoinListener.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
[23:19:19] [Server thread/INFO]: [+] ShulkerBox
[23:19:23] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7145ms or 142 ticks behind
[23:19:23] [Server thread/WARN]: [UltimateStacker] Loaded class us.myles.ViaVersion.api.Via from ViaVersion v3.0.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
[23:19:27] [Server thread/INFO]: ShulkerBox issued server command: /ar check member
[23:19:27] [Craft Scheduler Thread - 36/WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.commands.manager.AutorankCommand.lambda$runCommandTask$1(AutorankCommand.java:115)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
[23:19:19] [Server thread/INFO]: [+] ShulkerBox
[23:19:23] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 7145ms or 142 ticks behind
[23:19:23] [Server thread/WARN]: [UltimateStacker] Loaded class us.myles.ViaVersion.api.Via from ViaVersion v3.0.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
[23:19:27] [Server thread/INFO]: ShulkerBox issued server command: /ar check member
[23:19:27] [Craft Scheduler Thread - 36/WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.commands.manager.AutorankCommand.lambda$runCommandTask$1(AutorankCommand.java:115)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: Caused by: java.lang.NullPointerException
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.staartvin.plugins.pluginlibrary.hooks.QuestsHook.getQuester(QuestsHook.java:57)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.staartvin.plugins.pluginlibrary.hooks.QuestsHook.isQuestCompleted(QuestsHook.java:120)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.pathbuilder.requirement.QuestsCompleteSpecificQuestRequirement.meetsRequirement(QuestsCompleteSpecificQuestRequirement.java:30)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.pathbuilder.requirement.AbstractRequirement.isMet(AbstractRequirement.java:199)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.pathbuilder.holders.CompositeRequirement.meetsRequirement(CompositeRequirement.java:281)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.pathbuilder.Path.meetsAllRequirements(Path.java:303)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.pathbuilder.Path.checkPathProgress(Path.java:147)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:53)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.commands.CheckCommand.showSpecificPath(CheckCommand.java:86)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.commands.CheckCommand.lambda$onCommand$1(CheckCommand.java:315)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:294)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:124)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[23:19:27] [Craft Scheduler Thread - 36/WARN]: ... 1 more
```
I'd really appreciate an update to have Quests function properly with AutoRank as having players complete certain quests for each rank is planned to be a key part of my server's rank progression. From what I heard this is due to an API change or something in Quests when 1.15 came. I do not know for sure, but if you could tend to this issue before the next update it would be greatly appreciated.
Thank you!
- JpCuber

**Comment by Staartvin** [comment]
Which Quests plugin are you using? Can you link to the Spigot page?
