### ISSUE TITLE
Essentialsx.isAFK Error

### ISSUE THREAD

**Issue by owen-22** [Staartvin/Autorank-2#738]
I have no idea why but the EssentialsX hook to check for AFK players has suddenly started throwing this error out of the blue:

`[13:22:12] [Craft Scheduler Thread - 78/WARN]: [Autorank] Plugin Autorank v4.3.3 generated an exception while executing task 56681
java.lang.NullPointerException: null
	at me.staartvin.plugins.pluginlibrary.hooks.EssentialsXHook.isAFK(EssentialsXHook.java:92) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:107) ~[?:?]
	at me.armar.plugins.autorank.playtimes.UpdateTimePlayedTask.run(UpdateTimePlayedTask.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-260]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-260]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-260]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

There were no changes to any Autorank settings or paths any time recently before this. Any clue what could be going wrong here?

**Comment by Staartvin** [comment]
It seems you were running an experimental version. I found that bug a few evenings ago and I fixed it. Try this new build and let me know if it worked for you: http://staartvin.com:8080/job/Autorank/82/

**Comment by owen-22** [comment]
This seems to have fixed it, thanks.
