### ISSUE TITLE
Issue with Towny dependency

### ISSUE THREAD

**Issue by metallnt** [Staartvin/Autorank-2#746]
Don't understand wot it...
Version 1.16.1 Spigot

`[Craft Scheduler Thread - 132/WARN]: [Autorank] Plugin Autorank v4.4-SNAPSHOT-108 generated an exception while executing task 56
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3137) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3342) ~[?:?]
	at java.lang.Class.newInstance(Class.java:556) ~[?:?]
	at me.staartvin.utils.pluginlibrary.Library.getHook(Library.java:110) ~[?:?]
	at me.staartvin.utils.pluginlibrary.PluginLibrary.getLibrary(PluginLibrary.java:43) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.getLibraryHook(DependencyManager.java:181) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:95) ~[?:?]
	at me.armar.plugins.autorank.playtimes.UpdateTimePlayedTask.run(UpdateTimePlayedTask.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 14 more
`

**Comment by Staartvin** [comment]
When does this error occur? Do you have Towny installed or are you using Towny requirements?

**Comment by metallnt** [comment]
The pattern of occurrence of the error is not found.  Towny do not use.  But there is a Reputation plugin.  He also introduces a hierarchy.  Maybe because of him.  I'll try to disable it today.

**Comment by metallnt** [comment]
When the server rebooted, Autorang issued a conflict with the PermissionsEX plugin, which is not supported. But at 1.15, everything worked perfectly. Apparently the whole problem was exactly that. I will look for another permission plugin.
Thanks

**Comment by metallnt** [comment]
After rearranging plugins and reconfiguring, the error did not recur.  I still do not understand what has towny to do with it, if it was not there.  I think the problem is solved.
