### ISSUE TITLE
Towny hook console spam

### ISSUE THREAD

**Issue by SXRWahrheit** [Staartvin/Autorank-2#749]
I don't use Towny. Nevertheless, AutoRank is flooding my console with this:

```
[10:20:59] [Craft Scheduler Thread - 32/WARN]: [Autorank] Plugin Autorank v4.4-SNAPSHOT-119 generated an exception while executing task 20173
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_191]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_191]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_191]
	at me.staartvin.utils.pluginlibrary.Library.getHook(Library.java:110) ~[?:?]
	at me.staartvin.utils.pluginlibrary.PluginLibrary.getLibrary(PluginLibrary.java:43) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.getLibraryHook(DependencyManager.java:157) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:69) ~[?:?]
	at me.armar.plugins.autorank.playtimes.UpdateTimePlayedTask.run(UpdateTimePlayedTask.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-116]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-116]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-116]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-116]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-116]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	... 15 more
```
```
[Sun, 9. Aug 2020 10:19:55 CDT INFO] Statz version 1.6-SNAPSHOT-30
[Sun, 9. Aug 2020 10:19:56 CDT INFO] Autorank version 4.4-SNAPSHOT-119
[Sun, 9. Aug 2020 10:19:57 CDT INFO] This server is running Paper version git-Paper-116 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

**Comment by PsiCoTixOG** [comment]
I'm having similar behaviour yet regarding RPGme

`14:37:16] [Craft Scheduler Thread - 23/WARN]: [Autorank] Plugin Autorank v4.4-SNAPSHOT-108 generated an exception while executing task 524
java.lang.NoClassDefFoundError: us/eunoians/mcrpg/api/exceptions/McRPGPlayerNotFoundException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_66]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_66]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_66]
	at me.staartvin.utils.pluginlibrary.Library.getHook(Library.java:110) ~[?:?]
	at me.staartvin.utils.pluginlibrary.PluginLibrary.getLibrary(PluginLibrary.java:43) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.getLibraryHook(DependencyManager.java:181) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:95) ~[?:?]
	at me.armar.plugins.autorank.playtimes.UpdateTimePlayedTask.run(UpdateTimePlayedTask.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot1.16.3.jar:git-Spigot-17d78db-2577f9b]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot1.16.3.jar:git-Spigot-17d78db-2577f9b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: us.eunoians.mcrpg.api.exceptions.McRPGPlayerNotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot1.16.3.jar:git-Spigot-17d78db-2577f9b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot1.16.3.jar:git-Spigot-17d78db-2577f9b]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
	... 14 more`

**Comment by nunavailabul** [comment]
Same problem

server is running Paper version git-Paper-267 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
AR Version: 4.4-SNAPSHOT-108

[20:58:42 WARN]: [Autorank] Plugin Autorank v4.4-SNAPSHOT-108 generated an exception while executing task 372
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_131]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_131]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_131]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_131]
        at me.staartvin.utils.pluginlibrary.Library.getHook(Library.java:110) ~[?:?]
        at me.staartvin.utils.pluginlibrary.PluginLibrary.getLibrary(PluginLibrary.java:43) ~[?:?]
        at me.armar.plugins.autorank.hooks.DependencyManager.getLibraryHook(DependencyManager.java:181) ~[?:?]
        at me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:95) ~[?:?]
        at me.armar.plugins.autorank.playtimes.UpdateTimePlayedTask.run(UpdateTimePlayedTask.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-267]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-267]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-267]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        ... 15 more

**Comment by Garrett1199** [comment]
Also having the same problem.
Having the same error running Spigot 1.16.4 and 1.16.5

`[18:30:40] [Craft Scheduler Thread - 17/WARN]: [Autorank] Plugin Autorank v4.4-SNAPSHOT-108 generated an exception while executing task 57
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/NotRegisteredException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_271]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_271]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_271]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
        at me.staartvin.utils.pluginlibrary.Library.getHook(Library.java:110) ~[?:?]
        at me.staartvin.utils.pluginlibrary.PluginLibrary.getLibrary(PluginLibrary.java:43) ~[?:?]
        at me.armar.plugins.autorank.hooks.DependencyManager.getLibraryHook(DependencyManager.java:181) ~[?:?]
        at me.armar.plugins.autorank.hooks.DependencyManager.isAFK(DependencyManager.java:95) ~[?:?]
        at me.armar.plugins.autorank.playtimes.UpdateTimePlayedTask.run(UpdateTimePlayedTask.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:2991-Spigot-018b9a0-f3f3094]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_271]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.NotRegisteredException
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        ... 14 more`

**Comment by SXRWahrheit** [comment]
I ended up writing my own auto-rank solution because this spam was unbearable, sorry. Someone else can take ownership of the issue.
